version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: kobiekabo/iss_tracker_midterm:1.0
        ports:
                - 5000:5000
